name: robustremedy
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 15.4.2+68

environment:
  sdk: ">=2.12.0 <4.1.0"

dependencies:
  flutter:
    sdk: flutter
  provider:
  vector_math: any
  flutter_swiper_null_safety: ^1.0.2
  flutter_svg: ^1.0.0
  scoped_model:
  localstorage: ^4.0.1+4
  cupertino_icons: ^1.0.5
  #carousel_pro: ^1.0.0
  #carousel_pro_nullsafety: ^2.0.0
  google_fonts:

  badges: ^2.0.3
  toast:
  shared_preferences:
  flutter_form_builder:
  geolocator: ^10.0.0
  geocoding: ^2.1.0
  #flutter_open_whatsapp: ^0.1.2
  font_awesome_flutter:
  double_back_to_close_app:
  flutter_html:
  material_floating_search_bar: ^0.3.6
  file_picker: 5.2.0
  dio: ^5.3.2
  path:
  translator:
  filter_list:
  modal_bottom_sheet: ^2.1.2
  flutter_local_notifications: ^15.1.0+1
  timelines: ^0.1.0
  get_it:
  url_launcher:
  flutter_rating_bar:
  share:
  flutter_xlider: ^3.5.0
  showcaseview:
  bouncing_widget:
  flutter_phone_direct_caller:
  webview_flutter:
  flutter_typeahead:
  image_picker: ^1.0.2
  change_app_package_name: ^1.0.0
  dropdown_search: ^5.0.6
  arabic_numbers: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3

flutter_icons:
  ios: true
  android: true
  image_path: "assets/Appicon.png"

dependency_overrides:
  modal_bottom_sheet: ^3.0.0-pre

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    - assets/Drawer/
    - assets/Login/
    - assets/icons/
    - assets/intro/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
